package timezone

// Generated from the IANA tz database (zone.tab + iso3166.tab); do not edit by hand.

type zone struct {
	name    string
	country string
}

var zones = []zone{
	{"Africa/Abidjan", "Côte d’Ivoire"},
	{"Africa/Accra", "Ghana"},
	{"Africa/Addis_Ababa", "Ethiopia"},
	{"Africa/Algiers", "Algeria"},
	{"Africa/Asmara", "Eritrea"},
	{"Africa/Asmera", ""},
	{"Africa/Bamako", "Mali"},
	{"Africa/Bangui", "Central African Rep."},
	{"Africa/Banjul", "Gambia"},
	{"Africa/Bissau", "Guinea-Bissau"},
	{"Africa/Blantyre", "Malawi"},
	{"Africa/Brazzaville", "Congo (Rep.)"},
	{"Africa/Bujumbura", "Burundi"},
	{"Africa/Cairo", "Egypt"},
	{"Africa/Casablanca", "Morocco"},
	{"Africa/Ceuta", "Spain"},
	{"Africa/Conakry", "Guinea"},
	{"Africa/Dakar", "Senegal"},
	{"Africa/Dar_es_Salaam", "Tanzania"},
	{"Africa/Djibouti", "Djibouti"},
	{"Africa/Douala", "Cameroon"},
	{"Africa/El_Aaiun", "Western Sahara"},
	{"Africa/Freetown", "Sierra Leone"},
	{"Africa/Gaborone", "Botswana"},
	{"Africa/Harare", "Zimbabwe"},
	{"Africa/Johannesburg", "South Africa"},
	{"Africa/Juba", "South Sudan"},
	{"Africa/Kampala", "Uganda"},
	{"Africa/Khartoum", "Sudan"},
	{"Africa/Kigali", "Rwanda"},
	{"Africa/Kinshasa", "Congo (Dem. Rep.)"},
	{"Africa/Lagos", "Nigeria"},
	{"Africa/Libreville", "Gabon"},
	{"Africa/Lome", "Togo"},
	{"Africa/Luanda", "Angola"},
	{"Africa/Lubumbashi", "Congo (Dem. Rep.)"},
	{"Africa/Lusaka", "Zambia"},
	{"Africa/Malabo", "Equatorial Guinea"},
	{"Africa/Maputo", "Mozambique"},
	{"Africa/Maseru", "Lesotho"},
	{"Africa/Mbabane", "Eswatini (Swaziland)"},
	{"Africa/Mogadishu", "Somalia"},
	{"Africa/Monrovia", "Liberia"},
	{"Africa/Nairobi", "Kenya"},
	{"Africa/Ndjamena", "Chad"},
	{"Africa/Niamey", "Niger"},
	{"Africa/Nouakchott", "Mauritania"},
	{"Africa/Ouagadougou", "Burkina Faso"},
	{"Africa/Porto-Novo", "Benin"},
	{"Africa/Sao_Tome", "Sao Tome & Principe"},
	{"Africa/Timbuktu", ""},
	{"Africa/Tripoli", "Libya"},
	{"Africa/Tunis", "Tunisia"},
	{"Africa/Windhoek", "Namibia"},
	{"America/Adak", "United States"},
	{"America/Anchorage", "United States"},
	{"America/Anguilla", "Anguilla"},
	{"America/Antigua", "Antigua & Barbuda"},
	{"America/Araguaina", "Brazil"},
	{"America/Argentina/Buenos_Aires", "Argentina"},
	{"America/Argentina/Catamarca", "Argentina"},
	{"America/Argentina/ComodRivadavia", ""},
	{"America/Argentina/Cordoba", "Argentina"},
	{"America/Argentina/Jujuy", "Argentina"},
	{"America/Argentina/La_Rioja", "Argentina"},
	{"America/Argentina/Mendoza", "Argentina"},
	{"America/Argentina/Rio_Gallegos", "Argentina"},
	{"America/Argentina/Salta", "Argentina"},
	{"America/Argentina/San_Juan", "Argentina"},
	{"America/Argentina/San_Luis", "Argentina"},
	{"America/Argentina/Tucuman", "Argentina"},
	{"America/Argentina/Ushuaia", "Argentina"},
	{"America/Aruba", "Aruba"},
	{"America/Asuncion", "Paraguay"},
	{"America/Atikokan", "Canada"},
	{"America/Atka", ""},
	{"America/Bahia", "Brazil"},
	{"America/Bahia_Banderas", "Mexico"},
	{"America/Barbados", "Barbados"},
	{"America/Belem", "Brazil"},
	{"America/Belize", "Belize"},
	{"America/Blanc-Sablon", "Canada"},
	{"America/Boa_Vista", "Brazil"},
	{"America/Bogota", "Colombia"},
	{"America/Boise", "United States"},
	{"America/Buenos_Aires", ""},
	{"America/Cambridge_Bay", "Canada"},
	{"America/Campo_Grande", "Brazil"},
	{"America/Cancun", "Mexico"},
	{"America/Caracas", "Venezuela"},
	{"America/Catamarca", ""},
	{"America/Cayenne", "French Guiana"},
	{"America/Cayman", "Cayman Islands"},
	{"America/Chicago", "United States"},
	{"America/Chihuahua", "Mexico"},
	{"America/Ciudad_Juarez", "Mexico"},
	{"America/Coral_Harbour", ""},
	{"America/Cordoba", ""},
	{"America/Costa_Rica", "Costa Rica"},
	{"America/Coyhaique", "Chile"},
	{"America/Creston", "Canada"},
	{"America/Cuiaba", "Brazil"},
	{"America/Curacao", "Curaçao"},
	{"America/Danmarkshavn", "Greenland"},
	{"America/Dawson", "Canada"},
	{"America/Dawson_Creek", "Canada"},
	{"America/Denver", "United States"},
	{"America/Detroit", "United States"},
	{"America/Dominica", "Dominica"},
	{"America/Edmonton", "Canada"},
	{"America/Eirunepe", "Brazil"},
	{"America/El_Salvador", "El Salvador"},
	{"America/Ensenada", ""},
	{"America/Fort_Nelson", "Canada"},
	{"America/Fort_Wayne", ""},
	{"America/Fortaleza", "Brazil"},
	{"America/Glace_Bay", "Canada"},
	{"America/Godthab", ""},
	{"America/Goose_Bay", "Canada"},
	{"America/Grand_Turk", "Turks & Caicos Is"},
	{"America/Grenada", "Grenada"},
	{"America/Guadeloupe", "Guadeloupe"},
	{"America/Guatemala", "Guatemala"},
	{"America/Guayaquil", "Ecuador"},
	{"America/Guyana", "Guyana"},
	{"America/Halifax", "Canada"},
	{"America/Havana", "Cuba"},
	{"America/Hermosillo", "Mexico"},
	{"America/Indiana/Indianapolis", "United States"},
	{"America/Indiana/Knox", "United States"},
	{"America/Indiana/Marengo", "United States"},
	{"America/Indiana/Petersburg", "United States"},
	{"America/Indiana/Tell_City", "United States"},
	{"America/Indiana/Vevay", "United States"},
	{"America/Indiana/Vincennes", "United States"},
	{"America/Indiana/Winamac", "United States"},
	{"America/Indianapolis", ""},
	{"America/Inuvik", "Canada"},
	{"America/Iqaluit", "Canada"},
	{"America/Jamaica", "Jamaica"},
	{"America/Jujuy", ""},
	{"America/Juneau", "United States"},
	{"America/Kentucky/Louisville", "United States"},
	{"America/Kentucky/Monticello", "United States"},
	{"America/Knox_IN", ""},
	{"America/Kralendijk", "Caribbean NL"},
	{"America/La_Paz", "Bolivia"},
	{"America/Lima", "Peru"},
	{"America/Los_Angeles", "United States"},
	{"America/Louisville", ""},
	{"America/Lower_Princes", "St Maarten (Dutch)"},
	{"America/Maceio", "Brazil"},
	{"America/Managua", "Nicaragua"},
	{"America/Manaus", "Brazil"},
	{"America/Marigot", "St Martin (French)"},
	{"America/Martinique", "Martinique"},
	{"America/Matamoros", "Mexico"},
	{"America/Mazatlan", "Mexico"},
	{"America/Mendoza", ""},
	{"America/Menominee", "United States"},
	{"America/Merida", "Mexico"},
	{"America/Metlakatla", "United States"},
	{"America/Mexico_City", "Mexico"},
	{"America/Miquelon", "St Pierre & Miquelon"},
	{"America/Moncton", "Canada"},
	{"America/Monterrey", "Mexico"},
	{"America/Montevideo", "Uruguay"},
	{"America/Montreal", ""},
	{"America/Montserrat", "Montserrat"},
	{"America/Nassau", "Bahamas"},
	{"America/New_York", "United States"},
	{"America/Nipigon", ""},
	{"America/Nome", "United States"},
	{"America/Noronha", "Brazil"},
	{"America/North_Dakota/Beulah", "United States"},
	{"America/North_Dakota/Center", "United States"},
	{"America/North_Dakota/New_Salem", "United States"},
	{"America/Nuuk", "Greenland"},
	{"America/Ojinaga", "Mexico"},
	{"America/Panama", "Panama"},
	{"America/Pangnirtung", ""},
	{"America/Paramaribo", "Suriname"},
	{"America/Phoenix", "United States"},
	{"America/Port-au-Prince", "Haiti"},
	{"America/Port_of_Spain", "Trinidad & Tobago"},
	{"America/Porto_Acre", ""},
	{"America/Porto_Velho", "Brazil"},
	{"America/Puerto_Rico", "Puerto Rico"},
	{"America/Punta_Arenas", "Chile"},
	{"America/Rainy_River", ""},
	{"America/Rankin_Inlet", "Canada"},
	{"America/Recife", "Brazil"},
	{"America/Regina", "Canada"},
	{"America/Resolute", "Canada"},
	{"America/Rio_Branco", "Brazil"},
	{"America/Rosario", ""},
	{"America/Santa_Isabel", ""},
	{"America/Santarem", "Brazil"},
	{"America/Santiago", "Chile"},
	{"America/Santo_Domingo", "Dominican Republic"},
	{"America/Sao_Paulo", "Brazil"},
	{"America/Scoresbysund", "Greenland"},
	{"America/Shiprock", ""},
	{"America/Sitka", "United States"},
	{"America/St_Barthelemy", "St Barthelemy"},
	{"America/St_Johns", "Canada"},
	{"America/St_Kitts", "St Kitts & Nevis"},
	{"America/St_Lucia", "St Lucia"},
	{"America/St_Thomas", "Virgin Islands (US)"},
	{"America/St_Vincent", "St Vincent"},
	{"America/Swift_Current", "Canada"},
	{"America/Tegucigalpa", "Honduras"},
	{"America/Thule", "Greenland"},
	{"America/Thunder_Bay", ""},
	{"America/Tijuana", "Mexico"},
	{"America/Toronto", "Canada"},
	{"America/Tortola", "Virgin Islands (UK)"},
	{"America/Vancouver", "Canada"},
	{"America/Virgin", ""},
	{"America/Whitehorse", "Canada"},
	{"America/Winnipeg", "Canada"},
	{"America/Yakutat", "United States"},
	{"America/Yellowknife", ""},
	{"Antarctica/Casey", "Antarctica"},
	{"Antarctica/Davis", "Antarctica"},
	{"Antarctica/DumontDUrville", "Antarctica"},
	{"Antarctica/Macquarie", "Australia"},
	{"Antarctica/Mawson", "Antarctica"},
	{"Antarctica/McMurdo", "Antarctica"},
	{"Antarctica/Palmer", "Antarctica"},
	{"Antarctica/Rothera", "Antarctica"},
	{"Antarctica/South_Pole", ""},
	{"Antarctica/Syowa", "Antarctica"},
	{"Antarctica/Troll", "Antarctica"},
	{"Antarctica/Vostok", "Antarctica"},
	{"Arctic/Longyearbyen", "Svalbard & Jan Mayen"},
	{"Asia/Aden", "Yemen"},
	{"Asia/Almaty", "Kazakhstan"},
	{"Asia/Amman", "Jordan"},
	{"Asia/Anadyr", "Russia"},
	{"Asia/Aqtau", "Kazakhstan"},
	{"Asia/Aqtobe", "Kazakhstan"},
	{"Asia/Ashgabat", "Turkmenistan"},
	{"Asia/Ashkhabad", ""},
	{"Asia/Atyrau", "Kazakhstan"},
	{"Asia/Baghdad", "Iraq"},
	{"Asia/Bahrain", "Bahrain"},
	{"Asia/Baku", "Azerbaijan"},
	{"Asia/Bangkok", "Thailand"},
	{"Asia/Barnaul", "Russia"},
	{"Asia/Beirut", "Lebanon"},
	{"Asia/Bishkek", "Kyrgyzstan"},
	{"Asia/Brunei", "Brunei"},
	{"Asia/Calcutta", ""},
	{"Asia/Chita", "Russia"},
	{"Asia/Choibalsan", ""},
	{"Asia/Chongqing", ""},
	{"Asia/Chungking", ""},
	{"Asia/Colombo", "Sri Lanka"},
	{"Asia/Dacca", ""},
	{"Asia/Damascus", "Syria"},
	{"Asia/Dhaka", "Bangladesh"},
	{"Asia/Dili", "East Timor"},
	{"Asia/Dubai", "United Arab Emirates"},
	{"Asia/Dushanbe", "Tajikistan"},
	{"Asia/Famagusta", "Cyprus"},
	{"Asia/Gaza", "Palestine"},
	{"Asia/Harbin", ""},
	{"Asia/Hebron", "Palestine"},
	{"Asia/Ho_Chi_Minh", "Vietnam"},
	{"Asia/Hong_Kong", "Hong Kong"},
	{"Asia/Hovd", "Mongolia"},
	{"Asia/Irkutsk", "Russia"},
	{"Asia/Istanbul", ""},
	{"Asia/Jakarta", "Indonesia"},
	{"Asia/Jayapura", "Indonesia"},
	{"Asia/Jerusalem", "Israel"},
	{"Asia/Kabul", "Afghanistan"},
	{"Asia/Kamchatka", "Russia"},
	{"Asia/Karachi", "Pakistan"},
	{"Asia/Kashgar", ""},
	{"Asia/Kathmandu", "Nepal"},
	{"Asia/Katmandu", ""},
	{"Asia/Khandyga", "Russia"},
	{"Asia/Kolkata", "India"},
	{"Asia/Krasnoyarsk", "Russia"},
	{"Asia/Kuala_Lumpur", "Malaysia"},
	{"Asia/Kuching", "Malaysia"},
	{"Asia/Kuwait", "Kuwait"},
	{"Asia/Macao", ""},
	{"Asia/Macau", "Macau"},
	{"Asia/Magadan", "Russia"},
	{"Asia/Makassar", "Indonesia"},
	{"Asia/Manila", "Philippines"},
	{"Asia/Muscat", "Oman"},
	{"Asia/Nicosia", "Cyprus"},
	{"Asia/Novokuznetsk", "Russia"},
	{"Asia/Novosibirsk", "Russia"},
	{"Asia/Omsk", "Russia"},
	{"Asia/Oral", "Kazakhstan"},
	{"Asia/Phnom_Penh", "Cambodia"},
	{"Asia/Pontianak", "Indonesia"},
	{"Asia/Pyongyang", "Korea (North)"},
	{"Asia/Qatar", "Qatar"},
	{"Asia/Qostanay", "Kazakhstan"},
	{"Asia/Qyzylorda", "Kazakhstan"},
	{"Asia/Rangoon", ""},
	{"Asia/Riyadh", "Saudi Arabia"},
	{"Asia/Saigon", ""},
	{"Asia/Sakhalin", "Russia"},
	{"Asia/Samarkand", "Uzbekistan"},
	{"Asia/Seoul", "Korea (South)"},
	{"Asia/Shanghai", "China"},
	{"Asia/Singapore", "Singapore"},
	{"Asia/Srednekolymsk", "Russia"},
	{"Asia/Taipei", "Taiwan"},
	{"Asia/Tashkent", "Uzbekistan"},
	{"Asia/Tbilisi", "Georgia"},
	{"Asia/Tehran", "Iran"},
	{"Asia/Tel_Aviv", ""},
	{"Asia/Thimbu", ""},
	{"Asia/Thimphu", "Bhutan"},
	{"Asia/Tokyo", "Japan"},
	{"Asia/Tomsk", "Russia"},
	{"Asia/Ujung_Pandang", ""},
	{"Asia/Ulaanbaatar", "Mongolia"},
	{"Asia/Ulan_Bator", ""},
	{"Asia/Urumqi", "China"},
	{"Asia/Ust-Nera", "Russia"},
	{"Asia/Vientiane", "Laos"},
	{"Asia/Vladivostok", "Russia"},
	{"Asia/Yakutsk", "Russia"},
	{"Asia/Yangon", "Myanmar (Burma)"},
	{"Asia/Yekaterinburg", "Russia"},
	{"Asia/Yerevan", "Armenia"},
	{"Atlantic/Azores", "Portugal"},
	{"Atlantic/Bermuda", "Bermuda"},
	{"Atlantic/Canary", "Spain"},
	{"Atlantic/Cape_Verde", "Cape Verde"},
	{"Atlantic/Faeroe", ""},
	{"Atlantic/Faroe", "Faroe Islands"},
	{"Atlantic/Jan_Mayen", ""},
	{"Atlantic/Madeira", "Portugal"},
	{"Atlantic/Reykjavik", "Iceland"},
	{"Atlantic/South_Georgia", "South Georgia & the South Sandwich Islands"},
	{"Atlantic/St_Helena", "St Helena"},
	{"Atlantic/Stanley", "Falkland Islands"},
	{"Australia/ACT", ""},
	{"Australia/Adelaide", "Australia"},
	{"Australia/Brisbane", "Australia"},
	{"Australia/Broken_Hill", "Australia"},
	{"Australia/Canberra", ""},
	{"Australia/Currie", ""},
	{"Australia/Darwin", "Australia"},
	{"Australia/Eucla", "Australia"},
	{"Australia/Hobart", "Australia"},
	{"Australia/LHI", ""},
	{"Australia/Lindeman", "Australia"},
	{"Australia/Lord_Howe", "Australia"},
	{"Australia/Melbourne", "Australia"},
	{"Australia/NSW", ""},
	{"Australia/North", ""},
	{"Australia/Perth", "Australia"},
	{"Australia/Queensland", ""},
	{"Australia/South", ""},
	{"Australia/Sydney", "Australia"},
	{"Australia/Tasmania", ""},
	{"Australia/Victoria", ""},
	{"Australia/West", ""},
	{"Australia/Yancowinna", ""},
	{"Brazil/Acre", ""},
	{"Brazil/DeNoronha", ""},
	{"Brazil/East", ""},
	{"Brazil/West", ""},
	{"Canada/Atlantic", ""},
	{"Canada/Central", ""},
	{"Canada/Eastern", ""},
	{"Canada/Mountain", ""},
	{"Canada/Newfoundland", ""},
	{"Canada/Pacific", ""},
	{"Canada/Saskatchewan", ""},
	{"Canada/Yukon", ""},
	{"Chile/Continental", ""},
	{"Chile/EasterIsland", ""},
	{"Europe/Amsterdam", "Netherlands"},
	{"Europe/Andorra", "Andorra"},
	{"Europe/Astrakhan", "Russia"},
	{"Europe/Athens", "Greece"},
	{"Europe/Belfast", ""},
	{"Europe/Belgrade", "Serbia"},
	{"Europe/Berlin", "Germany"},
	{"Europe/Bratislava", "Slovakia"},
	{"Europe/Brussels", "Belgium"},
	{"Europe/Bucharest", "Romania"},
	{"Europe/Budapest", "Hungary"},
	{"Europe/Busingen", "Germany"},
	{"Europe/Chisinau", "Moldova"},
	{"Europe/Copenhagen", "Denmark"},
	{"Europe/Dublin", "Ireland"},
	{"Europe/Gibraltar", "Gibraltar"},
	{"Europe/Guernsey", "Guernsey"},
	{"Europe/Helsinki", "Finland"},
	{"Europe/Isle_of_Man", "Isle of Man"},
	{"Europe/Istanbul", "Turkey"},
	{"Europe/Jersey", "Jersey"},
	{"Europe/Kaliningrad", "Russia"},
	{"Europe/Kiev", ""},
	{"Europe/Kirov", "Russia"},
	{"Europe/Kyiv", "Ukraine"},
	{"Europe/Lisbon", "Portugal"},
	{"Europe/Ljubljana", "Slovenia"},
	{"Europe/London", "Britain (UK)"},
	{"Europe/Luxembourg", "Luxembourg"},
	{"Europe/Madrid", "Spain"},
	{"Europe/Malta", "Malta"},
	{"Europe/Mariehamn", "Åland Islands"},
	{"Europe/Minsk", "Belarus"},
	{"Europe/Monaco", "Monaco"},
	{"Europe/Moscow", "Russia"},
	{"Europe/Nicosia", ""},
	{"Europe/Oslo", "Norway"},
	{"Europe/Paris", "France"},
	{"Europe/Podgorica", "Montenegro"},
	{"Europe/Prague", "Czech Republic"},
	{"Europe/Riga", "Latvia"},
	{"Europe/Rome", "Italy"},
	{"Europe/Samara", "Russia"},
	{"Europe/San_Marino", "San Marino"},
	{"Europe/Sarajevo", "Bosnia & Herzegovina"},
	{"Europe/Saratov", "Russia"},
	{"Europe/Simferopol", "Ukraine"},
	{"Europe/Skopje", "North Macedonia"},
	{"Europe/Sofia", "Bulgaria"},
	{"Europe/Stockholm", "Sweden"},
	{"Europe/Tallinn", "Estonia"},
	{"Europe/Tirane", "Albania"},
	{"Europe/Tiraspol", ""},
	{"Europe/Ulyanovsk", "Russia"},
	{"Europe/Uzhgorod", ""},
	{"Europe/Vaduz", "Liechtenstein"},
	{"Europe/Vatican", "Vatican City"},
	{"Europe/Vienna", "Austria"},
	{"Europe/Vilnius", "Lithuania"},
	{"Europe/Volgograd", "Russia"},
	{"Europe/Warsaw", "Poland"},
	{"Europe/Zagreb", "Croatia"},
	{"Europe/Zaporozhye", ""},
	{"Europe/Zurich", "Switzerland"},
	{"Indian/Antananarivo", "Madagascar"},
	{"Indian/Chagos", "British Indian Ocean Territory"},
	{"Indian/Christmas", "Christmas Island"},
	{"Indian/Cocos", "Cocos (Keeling) Islands"},
	{"Indian/Comoro", "Comoros"},
	{"Indian/Kerguelen", "French S. Terr."},
	{"Indian/Mahe", "Seychelles"},
	{"Indian/Maldives", "Maldives"},
	{"Indian/Mauritius", "Mauritius"},
	{"Indian/Mayotte", "Mayotte"},
	{"Indian/Reunion", "Réunion"},
	{"Mexico/BajaNorte", ""},
	{"Mexico/BajaSur", ""},
	{"Mexico/General", ""},
	{"Pacific/Apia", "Samoa (western)"},
	{"Pacific/Auckland", "New Zealand"},
	{"Pacific/Bougainville", "Papua New Guinea"},
	{"Pacific/Chatham", "New Zealand"},
	{"Pacific/Chuuk", "Micronesia"},
	{"Pacific/Easter", "Chile"},
	{"Pacific/Efate", "Vanuatu"},
	{"Pacific/Enderbury", ""},
	{"Pacific/Fakaofo", "Tokelau"},
	{"Pacific/Fiji", "Fiji"},
	{"Pacific/Funafuti", "Tuvalu"},
	{"Pacific/Galapagos", "Ecuador"},
	{"Pacific/Gambier", "French Polynesia"},
	{"Pacific/Guadalcanal", "Solomon Islands"},
	{"Pacific/Guam", "Guam"},
	{"Pacific/Honolulu", "United States"},
	{"Pacific/Johnston", ""},
	{"Pacific/Kanton", "Kiribati"},
	{"Pacific/Kiritimati", "Kiribati"},
	{"Pacific/Kosrae", "Micronesia"},
	{"Pacific/Kwajalein", "Marshall Islands"},
	{"Pacific/Majuro", "Marshall Islands"},
	{"Pacific/Marquesas", "French Polynesia"},
	{"Pacific/Midway", "US minor outlying islands"},
	{"Pacific/Nauru", "Nauru"},
	{"Pacific/Niue", "Niue"},
	{"Pacific/Norfolk", "Norfolk Island"},
	{"Pacific/Noumea", "New Caledonia"},
	{"Pacific/Pago_Pago", "Samoa (American)"},
	{"Pacific/Palau", "Palau"},
	{"Pacific/Pitcairn", "Pitcairn"},
	{"Pacific/Pohnpei", "Micronesia"},
	{"Pacific/Ponape", ""},
	{"Pacific/Port_Moresby", "Papua New Guinea"},
	{"Pacific/Rarotonga", "Cook Islands"},
	{"Pacific/Saipan", "Northern Mariana Islands"},
	{"Pacific/Samoa", ""},
	{"Pacific/Tahiti", "French Polynesia"},
	{"Pacific/Tarawa", "Kiribati"},
	{"Pacific/Tongatapu", "Tonga"},
	{"Pacific/Truk", ""},
	{"Pacific/Wake", "US minor outlying islands"},
	{"Pacific/Wallis", "Wallis & Futuna"},
	{"Pacific/Yap", ""},
	{"US/Alaska", ""},
	{"US/Aleutian", ""},
	{"US/Arizona", ""},
	{"US/Central", ""},
	{"US/East-Indiana", ""},
	{"US/Eastern", ""},
	{"US/Hawaii", ""},
	{"US/Indiana-Starke", ""},
	{"US/Michigan", ""},
	{"US/Mountain", ""},
	{"US/Pacific", ""},
	{"US/Samoa", ""},
	{"UTC", ""},
}
